### ISSUE TITLE
Cannot open file [..\Resources\Cub.obj]

### ISSUE THREAD

**Issue by Rich2020** [gazben/TraceDemon#1]
Hi, I think a file '**Cube.obj**' is missing from the **resources** folder.

**Renderer.cpp**
scenes[0]->LoadObj(".\Resources\Cube.obj", ".\Resources\Cube3.mtl");

Any chance you could add it to the project?

Thanks,
Rich

**Comment by gazben** [comment]
Hello!

Sorry for the late response. I added the Cube.obj to the project.

Gazben

**Comment by Rich2020** [comment]
Hey! Thanks a lot! ;)
